FROM python:3.6-alpine

RUN pip3 install --upgrade redis jsonpickle requests flask minio


COPY rest-server.py /
EXPOSE	5000
WORKDIR /
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8


ENV	FLASK_APP=rest-server.py run -h 0.0.0.0 -p 5000

CMD	["python3", "rest-server.py"]