FROM ubuntu:20.04

RUN	DEBIAN_FRONTEND=noninteractive apt-get update -y && \
	apt-get install -yq --no-install-recommends \
	   git python3 python3-pip curl

RUN pip3 install --upgrade redis jsonpickle requests bs4 flask pymongo flask_cors Flask-PyMongo pika pyyaml ua-parser user-agents fake-useragent

COPY rest-server.py /
EXPOSE	5000
WORKDIR /
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8

ENV	FLASK_APP=rest-server.py

CMD	["python3", "rest-server.py"]